packages:
  - "apps/*"
  - "packages/*"
  - "services/*"

allowBuilds:
  "@nestjs/core": true
  "@swc/core": true
  "esbuild": true
  "sharp": true
  "unrs-resolver": true
  "@sentry/node-cpu-profiler": true
