-- Exécutez ce code dans l'éditeur SQL de votre tableau de bord Supabase

CREATE TABLE IF NOT EXISTS public.password_resets (
    id bigint generated by default as identity primary key,
    phone text not null,
    school_slug text not null,
    otp text not null,
    expires_at timestamptz not null,
    created_at timestamptz default now()
);

-- Index pour accélérer la recherche
CREATE INDEX IF NOT EXISTS idx_password_resets_phone ON public.password_resets(phone);
