-- ============================================================
-- 🔒 MIGRATION P4 — SÉCURISATION, CONFINEMENT ET RPC ATOMIQUES
-- TABLE : public.password_resets
-- ============================================================
-- Ce script est transactionnel et idempotent.
-- Il convertit une table existante ou crée une nouvelle table,
-- purge les anciens OTP bruts historiques, impose l'unicité (phone, school_slug),
-- applique les contraintes strictes et implémente les RPC avec propriétaire postgres :
-- 1. request_password_reset_otp : verrouillage advisory + ON CONFLICT (3 req / 15 min).
-- 2. verify_and_consume_password_reset_otp : verrouillage FOR UPDATE, vérification
--    d'empreinte HMAC, GET DIAGNOSTICS ROW_COUNT et consommation unique anti-rejeu.
-- ============================================================

BEGIN;

-- 1. Création idempotente de la table password_resets si inexistante
CREATE TABLE IF NOT EXISTS public.password_resets (
    id bigint generated by default as identity primary key,
    phone text not null,
    school_slug text not null,
    otp varchar(64) not null,
    attempts integer not null default 0,
    request_count integer not null default 1,
    window_start timestamptz not null default now(),
    expires_at timestamptz not null,
    created_at timestamptz not null default now()
);

-- 2. Purge immédiate de toutes les anciennes demandes historiques
-- Les demandes de réinitialisation étant éphémères (15 min), cette purge garantit
-- l'élimination totale des anciens OTP bruts et permet l'ajout immédiat de la contrainte UNIQUE.
DELETE FROM public.password_resets;

-- 3. Ajout et conversion des colonnes pour une table préexistante
DO $$
BEGIN
    -- Colonne attempts
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'password_resets' AND column_name = 'attempts'
    ) THEN
        ALTER TABLE public.password_resets ADD COLUMN attempts integer not null default 0;
    END IF;

    -- Colonne request_count
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'password_resets' AND column_name = 'request_count'
    ) THEN
        ALTER TABLE public.password_resets ADD COLUMN request_count integer not null default 1;
    END IF;

    -- Colonne window_start
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'password_resets' AND column_name = 'window_start'
    ) THEN
        ALTER TABLE public.password_resets ADD COLUMN window_start timestamptz not null default now();
    END IF;
END $$;

-- Conversion du type de la colonne otp vers varchar(64) et NOT NULL
ALTER TABLE public.password_resets ALTER COLUMN otp TYPE varchar(64);
ALTER TABLE public.password_resets ALTER COLUMN otp SET NOT NULL;
ALTER TABLE public.password_resets ALTER COLUMN phone SET NOT NULL;
ALTER TABLE public.password_resets ALTER COLUMN school_slug SET NOT NULL;
ALTER TABLE public.password_resets ALTER COLUMN expires_at SET NOT NULL;

-- 4. Ajout idempotent des contraintes nommées
DO $$
BEGIN
    -- Contrainte d'unicité sur l'identité canonique (phone, school_slug)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'uq_password_resets_identity'
    ) THEN
        ALTER TABLE public.password_resets
        ADD CONSTRAINT uq_password_resets_identity UNIQUE (phone, school_slug);
    END IF;

    -- Contrainte sur le format strict du hash HMAC-SHA256 (64 caractères hexadécimaux minuscules)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_password_resets_otp_hex'
    ) THEN
        ALTER TABLE public.password_resets
        ADD CONSTRAINT chk_password_resets_otp_hex CHECK (length(otp) = 64 AND otp ~ '^[0-9a-f]{64}$');
    END IF;

    -- Contrainte sur le nombre maximal de tentatives (0 à 5)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_password_resets_attempts'
    ) THEN
        ALTER TABLE public.password_resets
        ADD CONSTRAINT chk_password_resets_attempts CHECK (attempts >= 0 AND attempts <= 5);
    END IF;

    -- Contrainte sur le nombre maximal de demandes par fenêtre (1 à 3)
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_password_resets_request_count'
    ) THEN
        ALTER TABLE public.password_resets
        ADD CONSTRAINT chk_password_resets_request_count CHECK (request_count >= 1 AND request_count <= 3);
    END IF;
END $$;

-- 5. Indexation composite
CREATE INDEX IF NOT EXISTS idx_password_resets_phone_created
    ON public.password_resets(phone, created_at DESC);

-- 6. Activation stricte de Row Level Security (RLS)
ALTER TABLE public.password_resets ENABLE ROW LEVEL SECURITY;

-- 7. Révocation totale des privilèges publics et anonymes sur la table
REVOKE ALL ON TABLE public.password_resets FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.password_resets TO service_role, postgres;

-- 8. Politique de service_role exclusive
DROP POLICY IF EXISTS service_role_full_access_password_resets ON public.password_resets;
CREATE POLICY service_role_full_access_password_resets
    ON public.password_resets
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- ------------------------------------------------------------
-- 9. RPC ATOMIQUE : Création sécurisée d'une demande OTP
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.request_password_reset_otp(
    p_phone text,
    p_school_slug text,
    p_otp_hash text,
    p_expires_at timestamptz
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
    v_clean_phone text;
    v_clean_slug text;
    v_record RECORD;
    v_new_req_count integer;
    v_win_start timestamptz;
BEGIN
    v_clean_phone := trim(p_phone);
    v_clean_slug := lower(trim(p_school_slug));

    -- Verrouillage transactionnel advisory sur l'identité canonique (phone:slug)
    PERFORM pg_catalog.pg_advisory_xact_lock(hashtext(v_clean_phone || ':' || v_clean_slug));

    -- Recherche de la ligne unique existante sous FOR UPDATE
    SELECT id, request_count, window_start, expires_at
    INTO v_record
    FROM public.password_resets
    WHERE phone = v_clean_phone
      AND school_slug = v_clean_slug
    FOR UPDATE;

    IF FOUND THEN
        -- Vérification si la fenêtre de 15 minutes est toujours active
        IF v_record.window_start >= (now() - interval '15 minutes') THEN
            IF v_record.request_count >= 3 THEN
                RETURN jsonb_build_object(
                    'success', false,
                    'reason', 'RATE_LIMIT_EXCEEDED',
                    'retry_after', GREATEST(1, EXTRACT(EPOCH FROM (v_record.window_start + interval '15 minutes' - now()))::integer)
                );
            ELSE
                v_new_req_count := v_record.request_count + 1;
                v_win_start := v_record.window_start;
            END IF;
        ELSE
            -- Fenêtre expirée : réinitialisation du compteur
            v_new_req_count := 1;
            v_win_start := now();
        END IF;

        -- Remplacement atomique de l'OTP en conservant le compteur de la fenêtre
        UPDATE public.password_resets
        SET otp = p_otp_hash,
            attempts = 0,
            request_count = v_new_req_count,
            window_start = v_win_start,
            expires_at = p_expires_at,
            created_at = now()
        WHERE id = v_record.id;

    ELSE
        -- Première demande pour cette identité (protégée par ON CONFLICT)
        INSERT INTO public.password_resets (
            phone,
            school_slug,
            otp,
            attempts,
            request_count,
            window_start,
            expires_at,
            created_at
        ) VALUES (
            v_clean_phone,
            v_clean_slug,
            p_otp_hash,
            0,
            1,
            now(),
            p_expires_at,
            now()
        )
        ON CONFLICT (phone, school_slug) DO UPDATE
        SET otp = EXCLUDED.otp,
            attempts = 0,
            request_count = CASE
                WHEN public.password_resets.window_start >= (now() - interval '15 minutes')
                THEN LEAST(3, public.password_resets.request_count + 1)
                ELSE 1
            END,
            window_start = CASE
                WHEN public.password_resets.window_start >= (now() - interval '15 minutes')
                THEN public.password_resets.window_start
                ELSE now()
            END,
            expires_at = EXCLUDED.expires_at,
            created_at = now();
    END IF;

    RETURN jsonb_build_object('success', true);
END;
$$;

-- ------------------------------------------------------------
-- 10. RPC ATOMIQUE : Vérification et consommation à usage unique
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.verify_and_consume_password_reset_otp(
    p_phone text,
    p_school_slug text,
    p_submitted_otp_hash text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, pg_temp
AS $$
DECLARE
    v_record RECORD;
    v_clean_phone text;
    v_clean_slug text;
    v_new_attempts integer;
    v_deleted_count integer;
BEGIN
    v_clean_phone := trim(p_phone);
    v_clean_slug := lower(trim(p_school_slug));

    -- Recherche et verrouillage exclusif de la ligne unique (SELECT ... FOR UPDATE)
    SELECT id, otp, attempts, expires_at
    INTO v_record
    FROM public.password_resets
    WHERE phone = v_clean_phone
      AND school_slug = v_clean_slug
    FOR UPDATE;

    -- Cas 1 : Aucun enregistrement trouvé
    IF NOT FOUND THEN
        RETURN jsonb_build_object(
            'success', false,
            'reason', 'NOT_FOUND_OR_EXPIRED'
        );
    END IF;

    -- Cas 2 : Code expiré
    IF v_record.expires_at < now() THEN
        DELETE FROM public.password_resets WHERE id = v_record.id;
        RETURN jsonb_build_object(
            'success', false,
            'reason', 'EXPIRED'
        );
    END IF;

    -- Cas 3 : Nombre maximal de tentatives déjà atteint
    IF v_record.attempts >= 5 THEN
        DELETE FROM public.password_resets WHERE id = v_record.id;
        RETURN jsonb_build_object(
            'success', false,
            'reason', 'MAX_ATTEMPTS_EXCEEDED'
        );
    END IF;

    -- Cas 4 : Empreinte OTP valide -> Consommation atomique immédiate avec vérification ROW_COUNT
    IF v_record.otp = p_submitted_otp_hash THEN
        DELETE FROM public.password_resets WHERE id = v_record.id;
        GET DIAGNOSTICS v_deleted_count = ROW_COUNT;

        IF v_deleted_count = 1 THEN
            RETURN jsonb_build_object('success', true);
        ELSE
            RETURN jsonb_build_object(
                'success', false,
                'reason', 'CONCURRENT_CONSUMPTION_DETECTED'
            );
        END IF;
    END IF;

    -- Cas 5 : Empreinte OTP invalide -> Incrément atomique ou suppression à 5 échecs
    v_new_attempts := v_record.attempts + 1;
    IF v_new_attempts >= 5 THEN
        DELETE FROM public.password_resets WHERE id = v_record.id;
        RETURN jsonb_build_object(
            'success', false,
            'reason', 'MAX_ATTEMPTS_EXCEEDED'
        );
    ELSE
        UPDATE public.password_resets
        SET attempts = v_new_attempts
        WHERE id = v_record.id;

        RETURN jsonb_build_object(
            'success', false,
            'reason', 'INVALID_OTP',
            'attempts', v_new_attempts
        );
    END IF;
END;
$$;

-- 11. Attribution explicite du propriétaire postgres
ALTER FUNCTION public.request_password_reset_otp(text, text, text, timestamptz) OWNER TO postgres;
ALTER FUNCTION public.verify_and_consume_password_reset_otp(text, text, text) OWNER TO postgres;

-- 12. Sécurisation des privilèges RPC
REVOKE ALL ON FUNCTION public.request_password_reset_otp(text, text, text, timestamptz) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.request_password_reset_otp(text, text, text, timestamptz) TO service_role, postgres;

REVOKE ALL ON FUNCTION public.verify_and_consume_password_reset_otp(text, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.verify_and_consume_password_reset_otp(text, text, text) TO service_role, postgres;

COMMIT;
